name: First Workflow
on: push
jobs: 
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Welcome Message
      run: echo "Welcome Print"
      
    - name: List Files
      run: ls -la 

    - name: Read Files
      run: cat README.md