name: First Workflow
on: push
jobs: 
  first_job:
    runs-on: ubuntu-latest
    steps: 
     - name: Welcome Message
       run: echo "Welcome Print"
      
     - name: List Files
       run: ls

     - name: Read Files
       run: cat README.md